module.exports =
    applayout: require './applayout'
    convlist:  require './convlist'
    messages:  require './messages'
    input:     require './input'
    conninfo:  require './conninfo'
    convadd:   require './convadd'
    controls:  require './controls'
    notifications: require './notifications'
    typinginfo: require './typinginfo'
    menu: require './menu'
    trayicon: require './trayicon'
    dockicon: require './dockicon'
