module.exports = [
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_BFF.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_BRB.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_FTW.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_GR8.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_ASAP.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_LMAO.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_LOL.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_Meh.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_NomNomNom.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_OMG.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_RAD.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_SeeULater.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_Sup.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_TTYL.png'
    'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_Yay.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Yum.png'
  'title': 'Internet'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Awesome.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Bye.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_CallMe.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Congrats.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Cool.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_EPIC.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_HaHaHa.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Hi.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Hmmm.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Hot.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_LoveU.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Thanks.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_WOW.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_XOXOXO.png'
    'https://www.gstatic.com/chat/stickers/pack2/Callouts_Positive_Yum.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack1/Callouts_Internet_Yay.png'
  'title': 'Positive'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Busy.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Crying.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Dancing.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Drunk.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Laughing.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Love.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Painful.png"'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Peace.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Scared.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Sick.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Sleeping.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_Sunbathing.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_TTYL.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_ThumbsUp.png'
    'https://www.gstatic.com/chat/stickers/pack3/Alien_WalkingDog.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack3/Alien_Angry.png'
  'title': 'Alien'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Baby.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Cleaning.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Crying.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Eating.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Furious.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_GoodLuck.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_HappyBday.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_HappyEaster.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Laughing.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Love.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Party.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Sad.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Scared.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Sleeping.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_TTYL.png'
    'https://www.gstatic.com/chat/stickers/pack4/Bunny_Yay.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack4/Bunny_Yay.png'
  'title': 'Bunny'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_DoNotDisturb.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Flowers.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Furious.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_HangingOut.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_HappyBDay.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_HaveFun.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Hey.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Hilarious.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Kiss.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Love.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_OnMyWay.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Oops.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Picnic.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Undecided.png'
    'https://www.gstatic.com/chat/stickers/pack5/Cat_Waiting.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack5/Cat_Hey.png'
  'title': 'Cat'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_CallMe.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Christmas.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_DealWithIt.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Eating.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Halloween.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Impatient.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Innocent.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Love.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_NewYear.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Rich.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Sad.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Sick.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Sleepy.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_StuckUp.png'
    'https://www.gstatic.com/chat/stickers/pack6/FatCat_Surprised.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack6/FatCat_Impatient.png'
  'title': 'FatCat'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_CallMe.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Crying.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Drink.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Eating.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_HappyBDay.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Help.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Laughing.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Love.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_MissYou.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Ouch.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Sick.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_Sleeping.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_TTYL.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_ThumbsUp.png'
    'https://www.gstatic.com/chat/stickers/pack7/Koala_What.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack7/Koala_Angry.png'
  'title': 'Koala'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Annoyed.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_BBQ.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Eating.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Flowers.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Hi.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Hiding.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Hurt.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Movies.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Sad.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Singing.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Sleepy.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Snow.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Sports.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Sunbathing.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_Washing.png'
    'https://www.gstatic.com/chat/stickers/pack8/Monstro_WorkingOut.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack8/Monstro_Hi.png'
  'title': 'Monstro'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Confused.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Drunk.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Eating.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Facepalm.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Help.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Laughing.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Love.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Painful.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Rich.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Searching.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Sick.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Snoozing.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_Sorry.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_TTYL.png'
    'https://www.gstatic.com/chat/stickers/pack9/Pirate_ThumbsUp.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack9/Pirate_Angry.png'
  'title': 'Pirate'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Cheering.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Crying.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Eating.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Facepalm.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Gift.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Groggy.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_HighFive.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Hug.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Music.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Ouch.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Party.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Please.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Scared.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Sleeping.png'
    'https://www.gstatic.com/chat/stickers/pack10/Penguins_Surprise.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack10/Penguins_Cheering.png'
  'title': 'Penguins'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_CoffeeBreak.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Dead.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Devious.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Gym.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Heartbroken.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Laughing.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Loser.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Love.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Mail.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Sick.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Sleeping.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Surprised.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_TalkToTheHand.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_ThumbsDown.png'
    'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_Tipsy.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack11/QueenCranky_ThumbsDown.png'
  'title': 'QueenCranky'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack12/Santa_Anger.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_CallMe.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_Confused.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_HeyHeyHey.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_HoHoHo.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_Kiss.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_LetsTalk.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_Love.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_Loved.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_MerryXmas.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_OnMyWay.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_Sleeping.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_StuckInAMeeting.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_Stuffed.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_ThumbsUp.png'
    'https://www.gstatic.com/chat/stickers/pack12/Santa_Vacation.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack12/Santa_HoHoHo.png'
  'title': 'Santa'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Coffee.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Cold.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_HappyBDay.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Karaoke.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Late.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Sleeping.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Spam.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Stuck.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Swamped.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Trashed.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Vacation.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Virus.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Workaholic.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_WorkDone.png'
    'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Yes.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack13/Skeleton_Late.png'
  'title': 'Skeleton'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_CallMe.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Confused.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Congrats.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Eating.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Loving.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_OnTheRoad.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_OutOfIt.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Relaxing.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Sad.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Shocked.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Sleepy.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Swamped.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Waving.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Working.png'
    'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Workout.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack14/TinyAstronaut_Shocked.png'
  'title': 'TinyAstronaut'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_BadJoke.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Bath.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Eating.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_HappyBday.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Jogging.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_LOL.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Lost.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Love.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_OnMyWay.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Scared.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Shopping.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Sick.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Sleep.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Walkies.png'
    'https://www.gstatic.com/chat/stickers/pack15/Turtle_Away.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack15/Turtle_Lost.png'
  'title': 'Turtle'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Angry.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_CallMe.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Crying.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Food.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Laugh.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Love.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Mess.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Ouch.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Rich.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Santa.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Sick.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Sleep.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_StPatricks.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_ThumbsUp.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Travelling.png'
    'https://www.gstatic.com/chat/stickers/pack16/Viking_Valentine.png'
  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack16/Viking_Food.png'
  'title': 'Viking'
  }
  {
  'range': [
    'https://www.gstatic.com/chat/stickers/pack17/01.HaloGuy_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/02.DoubleHighFive_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/03.HappyCrying_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/04.HappyBlushing_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/05.SleepyZZZ_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/06.Confused_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/07.OMGTerrified_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/08.OhNo_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/09.HeartEyed_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/10.Sunglasses_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/11.Praying_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/12.MumsTheWord_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/13.CatHeart_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/14.CatHappy_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/16.Princess_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/17.Ghost_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/18.SparklingHeart_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/21.ThumpingHeart_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/29.Cake_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/angry_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/winter_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/crying_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/frustrated_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/worried_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/happy_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/joy_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/kiss_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/lol_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/meh_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/sad_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/scared_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/sick_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/silly_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/smirk_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/wink_image.gif'
    'https://www.gstatic.com/chat/stickers/pack17/15.Poop_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/28.Celebration_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/23.FlexedArm_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/24.Cheers_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/30.Music_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/20.Thumbsdown_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/19.ThumbsUp_960x663.gif'
    'https://www.gstatic.com/chat/stickers/pack17/22.FistBump_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/25.Waving_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/26.Okay_640x442.gif'
    'https://www.gstatic.com/chat/stickers/pack17/27.Peace_640x442.gif'

  ]
  'representation': 'https://www.gstatic.com/chat/stickers/pack17/joy_image.gif'
  'title': 'Other'
  }

]
