name: yakyak # you probably want to 'snapcraft register <name>'
version: 1.4.3 # just for humans, typically '1.2+git' or '1.3.2'
summary: Desktop client for Google Hangouts
description: |
  YakYak is an open source cross platform client for Google Hangouts. 
  Based off the Electron framework, it uses your Google Account to
  remotely access your Google Hangouts messages, allowing you to use 
  Hangouts in a traditional instant messaging interface.
  YakYak is in no way associated with or endorsed by Google. 
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  yakyak:
    source: https://github.com/yakyak/yakyak.git
    plugin: nodejs

apps:
  yakyak:
    command: bin/yakyak
